# Generated by Django 5.0.dev20230213052949 on 2023-07-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/media/img_212915.png",
                null=True,
                upload_to="chat_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/media/img_212915.png",
                null=True,
                upload_to="user_photos/",
            ),
        ),
    ]
