# Generated by Django 5.0.dev20230213052949 on 2023-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
