# Generated by Django 5.0.dev20230213052949 on 2023-03-28 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="profile",
        ),
    ]
