# Generated by Django 5.0.dev20230213052949 on 2023-10-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_remove_chatmembers_left_att_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="group_chat",
            field=models.BooleanField(default=False),
        ),
    ]
