# Generated by Django 5.0.dev20230213052949 on 2023-10-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_chat_group_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="avatar",
            field=models.ImageField(
                default="media/chat_photos/default.jpg", upload_to="chat_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="media/user_photos/default.jpg", upload_to="user_photos/"
            ),
        ),
    ]
