# Generated by Django 5.0.dev20230213052949 on 2023-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_alter_chat_avatar_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="avatar",
            field=models.ImageField(
                default="chat_photos/default.jpg", upload_to="chat_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="user_photos/default.jpg", upload_to="user_photos/"
            ),
        ),
    ]
