# Generated by Django 5.0.dev20230213052949 on 2023-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_alter_chat_avatar_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="chat_photos/default.jpg",
                null=True,
                upload_to="chat_photos/",
            ),
        ),
    ]
