# Generated by Django 5.0.dev20230213052949 on 2024-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_alter_chat_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
