# Generated by Django 5.0.dev20230213052949 on 2024-02-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_alter_chat_chat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, unique=True
            ),
        ),
    ]
