# Generated by Django 5.0.dev20230213052949 on 2024-02-06 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0020_alter_chat_chat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="Имя не может быть пустым."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="Фамилия не может быть пустой."
                    )
                ],
            ),
        ),
    ]
