# Generated by Django 5.0.dev20230213052949 on 2024-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0021_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
