# Generated by Django 5.0.dev20230213052949 on 2024-05-02 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profanity.validators


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0025_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionlog",
            options={
                "verbose_name": "Журнал действий",
                "verbose_name_plural": "Журналы действий",
            },
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="chatadmins",
            options={
                "verbose_name": "Администратор чата",
                "verbose_name_plural": "Администраторы чата",
            },
        ),
        migrations.AlterModelOptions(
            name="chatmembers",
            options={
                "verbose_name": "Участник чата",
                "verbose_name_plural": "Участники чата",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(max_length=255, verbose_name="Тип действия"),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="target_object_id",
            field=models.PositiveIntegerField(verbose_name="ID объекта действия"),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="chat_photos/default.jpg",
                null=True,
                upload_to="chat_photos/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID чата"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="group_chat",
            field=models.BooleanField(
                default=False, verbose_name="Является ли групповым чатом"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время обновления"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="chatadmins",
            name="chat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
                verbose_name="ID чата",
            ),
        ),
        migrations.AlterField(
            model_name="chatadmins",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время становления администратором"
            ),
        ),
        migrations.AlterField(
            model_name="chatadmins",
            name="left_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время лишения прав администратора"
            ),
        ),
        migrations.AlterField(
            model_name="chatadmins",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="chatmembers",
            name="chat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
                verbose_name="ID чата",
            ),
        ),
        migrations.AlterField(
            model_name="chatmembers",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время присоединения"
            ),
        ),
        migrations.AlterField(
            model_name="chatmembers",
            name="left_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время выхода из чата"
            ),
        ),
        migrations.AlterField(
            model_name="chatmembers",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                validators=[profanity.validators.validate_is_profane],
                verbose_name="Содержание сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
                verbose_name="ID чата",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID отправителя",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время обновления"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="Имя не может быть пустым."
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="Фамилия не может быть пустой."
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время обновления"
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID подразделения",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "head_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID главы подразделения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.CreateModel(
            name="DepartmentEployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время присоединения"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время выхода из подразделения",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.department",
                        verbose_name="ID подразделения",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник подразделения",
                "verbose_name_plural": "Участники подразделения",
            },
        ),
    ]
