# Generated by Django 5.0.dev20230213052949 on 2024-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0026_alter_actionlog_options_alter_chat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.TextField(blank=True, verbose_name="Роль"),
        ),
    ]
