# Generated by Django 5.0.dev20230213052949 on 2024-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0027_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="departmenteployee",
            name="role",
            field=models.TextField(blank=True, verbose_name="Должность"),
        ),
    ]
