# Generated by Django 5.0.dev20230213052949 on 2024-05-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0028_remove_userprofile_role_departmenteployee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Содержание сообщения"),
        ),
    ]
