# Generated by Django 5.0.dev20230213052949 on 2024-05-09 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0029_alter_message_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "role_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID должности"
                    ),
                ),
                ("role_name", models.TextField(blank=True, verbose_name="Должность")),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время присоединения"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время выхода из подразделения",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.department",
                        verbose_name="ID подразделения",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.roles",
                        verbose_name="ID должности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник подразделения",
                "verbose_name_plural": "Участники подразделения",
            },
        ),
        migrations.DeleteModel(
            name="DepartmentEployee",
        ),
    ]
