# Generated by Django 5.0.dev20230213052949 on 2024-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0030_roles_departmentemployee_delete_departmenteployee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roles",
            options={"verbose_name": "Должность", "verbose_name_plural": "Должности"},
        ),
        migrations.AlterField(
            model_name="roles",
            name="role_name",
            field=models.TextField(blank=True, unique=True, verbose_name="Должность"),
        ),
    ]
