# Generated by Django 5.0.6 on 2024-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
